Prevent null Secret clientSecret in ServicePrincipal class
Encountered

```
java.lang.NullPointerException: Cannot invoke "hudson.util.Secret.getPlainText()" because "this.data.clientSecret" is null
	at PluginClassLoader for azure-credentials//com.microsoft.azure.util.AzureCredentials.getPlainClientSecret(AzureCredentials.java:654)
	at PluginClassLoader for azure-credentials//com.microsoft.azure.util.AzureCredentials.getTokenCredential(AzureCredentials.java:575)
	at PluginClassLoader for azure-credentials//com.microsoft.jenkins.credentials.AzureResourceManagerRetriever.getAzureResourceManager(AzureResourceManagerRetriever.java:45)
```

This is the only constructor that would allow a null for `Secret clientSecret`.